when:
  - event: cron
    cron: data-update
  - event: push
    branch: main

steps:
  fetch-data:
    image: python:3
    commands:
      - pip install -r ./data/requirements.txt
      - python ./data/aggregation.py
      - SHORT_SHA=$$(git rev-parse --short HEAD)
      - TIMESTAMP=$$(date -u +'%Y%m%d-%H%M')
      - >
        echo "{\"timestamp\": \"$$(date -u +'%Y-%m-%dT%H:%M:%SZ')\", \"version\": \"$$SHORT_SHA-$$TIMESTAMP\"}" > data/data/metadata.json

  commit-data:
    image: alpine/git
    environment:
      CB_TOKEN:
        from_secret: cb_token
    commands:
      - git config --global user.name "Woodpecker CI"
      - git config --global user.email "ci@codeberg.org"
      - git config --global --add safe.directory '*'
      - git remote set-url origin https://chric:$CB_TOKEN@codeberg.org/chric/rhygfuehl.git
      - git add data/data/*.json
      - git diff --quiet && git diff --staged --quiet || (git commit -m "cron data update [skip ci]" && git pull --rebase origin main && git push origin main)

  build:
    image: node:24
    commands:
      - npm ci
      - npm run build

  deploy-pages:
    image: alpine/git
    environment:
      CB_TOKEN:
        from_secret: cb_token
    commands:
      - git config --global user.name "Woodpecker CI"
      - git config --global user.email "ci@codeberg.org"
      - git config --global --add safe.directory '*'
      - git clone --branch pages https://chric:$CB_TOKEN@codeberg.org/chric/rhygfuehl.git output
      - rm -rf output/* output/.[!.]* output/..?*
      - cp -a dist/. output/
      - cd output
      - git add .
      - git diff --quiet && git diff --staged --quiet || git commit -m "Deploy pages"
      - git push origin pages

